### ISSUE TITLE
[coc.nvim]: UnhandledRejection: Vim(return):Error invoking 'python_execute' on channel 9 when using snippets after upgrading to v0.0.82

### ISSUE THREAD

**Issue by Frederick888** [neoclide/coc.nvim#3956]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-1d9a26af 2022-08-01 02:18:48 +0800
coc.nvim directory: /Users/frederick.zhang/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-08-01T18:22:33.243 INFO (pid:84426) [services] - registered service "languageserver.bash"
2022-08-01T18:22:33.245 INFO (pid:84426) [services] - registered service "languageserver.ccls"
2022-08-01T18:22:33.246 INFO (pid:84426) [services] - registered service "languageserver.cmake"
2022-08-01T18:22:33.246 INFO (pid:84426) [services] - registered service "languageserver.dockerfile"
2022-08-01T18:22:33.246 INFO (pid:84426) [services] - registered service "languageserver.jsonnet"
2022-08-01T18:22:33.246 INFO (pid:84426) [services] - registered service "languageserver.sql"
2022-08-01T18:22:33.314 INFO (pid:84426) [services] - registered service "diagnostic-languageserver"
2022-08-01T18:22:33.336 INFO (pid:84426) [services] - registered service "eslint"
2022-08-01T18:22:33.352 INFO (pid:84426) [services] - ESLint state change: stopped => starting
2022-08-01T18:22:33.938 INFO (pid:84426) [plugin] - coc.nvim initialized with node: v18.7.0 after 799ms
2022-08-01T18:22:33.944 WARN (pid:84426) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/Users/frederick.zhang/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/Users/frederick.zhang/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-08-01T18:22:34.042 INFO (pid:84426) [services] - ESLint state change: starting => running
2022-08-01T18:22:34.046 INFO (pid:84426) [services] - service eslint started
2022-08-01T18:22:39.497 INFO (pid:84426) [attach] - receive notification: showInfo []

```

## Describe the bug

When using coc-snippets with https://github.com/honza/vim-snippets, after upgrading to 6810b0b, I see the error below:

```
[coc.nvim]: UnhandledRejection: Vim(return):Error invoking 'python_execute' on channel 9 (python3-script-host):
Error on execute python code:
snip._reset("")
pattern = re.compile("lorem(([1-4])?[0-9])?")
match = pattern.search("")
snip.rv = " ".join(LOREM.split()[:int(match.group(1))]) if match.group(1) else LOREM
Error: request error on nvim_command - Vim(return):Error invoking 'python_execute' on channel 9 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 4, in <module>
AttributeError: 'NoneType' object has no attribute 'group'
    at xh (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:250:526)
    at LV (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:249:285451)
    at cs.resolve (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:258:2786)
    at ep.evalCodeBlocks (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:261:1656)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async lD.resolve (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:269:637)
    at async lD.init (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:269:306)
    at async cD.resolveSnippet (/Users/frederick.zhang/.vim/plugged/coc.nvim/build/index.js:270:6212)
```

be514c7 didn't have this issue.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath

  call plug#begin('~/.vim/plugged')
  Plug 'honza/vim-snippets'
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()

  if has('mac')
    let g:coc_node_path = '/usr/local/bin/node'
  else
    let g:coc_node_path = '/usr/bin/node'
  endif

  set nobackup
  set nowritebackup
  set cmdheight=2
  set updatetime=300
  ```

- Start (neo)vim with command: `nvim -u mini.vim hello.md`

- Type `lo`

## Screenshots (optional)

<img width="903" alt="image" src="https://user-images.githubusercontent.com/4507647/182106291-0b4529a8-2ec6-4123-a59c-5584bae136fa.png">
